### ISSUE TITLE
Issues 2/13

### ISSUE THREAD

**Issue by OhBall** [jcolla-holla/map_my_pun_real#2]
- [x] Background color should be grey for the main container.
- [ ] Inputs should have white background-color of white on focus.  **Jesse comment: I'm not sure what you mean - I believe this is already the case, see: http://localhost:3000/#/signup**
- [x] The way that form errors are being handled isn't great. While in-line errors is a difficult feature to implement, if a list of errors is presented they should be styled more than they currently are. `Error 1` could be replaced with just a bullet point, for instance.  
- [x] Text inputs are slightly too large.
- [x] Errors do not clear when navigating from the sign up page to the log in page, and vice-versa.
- [x] Font weight on  placeholder text is a little too high, although depending on the font you're using this may not be fixable.
- [x] Log In and Sign Up buttons in nav bar are too large.
- [x] Text in the nav bar is too large.  **Jesse comment: this is mostly attributable to different fonts. 
 The MapMyPun font is "Armour" which is trademarked by Under Armour.  The font I'm using for this is Roboto - it's close to Armour.  Increasing text in nav bar (if we are talking about the buttons like 'Create Workout', 'Log Workout', etc I think any smaller and they lose relevance on the page.**
- [x] Light grey portion of the footer is too tall

For the `SignUpForm`, the drop down needs:
  - [x] Extra padding to the left for the text.  **Jesse comment: this was a deliberate choice bc the select element doesn't have a simple solution for aligning the text center.  So 4 inputs with centered text and the bottom select element not having centered text looks bad.  Less bad in my opinion to have all inputs w text to the left**
  - [x] No border-radius.

The link in the top-right corner that takes you from login to signup (and vice-versa) should:
  - [x] Be two words (`Sign Up` rather than `SIGNUP`)
  - [x] Should change color on hover, rather than underline

**Comment by jcolla-holla** [comment]
- "The way that form errors are being handled isn't great...." --> I added _required_ to most input fields which apparently is a built-in browser in-line handler that prevents a user from ever getting to my rendered errors.
